### ISSUE TITLE
Pattern effects extension

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/BambooTracker#132]
This issue is the plan of effects expansion.

### Global
- [x] `0Xxx` `0Yxx` **Register address** - Set the address of register to write Register value.
- [x] `0Zxx` **Register value** - Write the value to the register.

### FM
- [x] `FBxx` **FB control** - Change FB.
- [x] `Axyy` **ARx control** - Change ARx (x is the operator number).
- [x] `Dxyy` **DRx control** - Change DRx (x is the operator number).
- [x] `Txyy` **TLx control** - Change TLx (x is the operator number).
- [x] `MLxy` **MLx control** - Change MLx (x is the operator number).
- [x] `RRxy` **RRx control** - Change RRx (x is the operator number).
- [x] `B0xx` **Brightness** - #118, change modulators TL.

### SSG
- [x] `0Vxx` **Tone/Noise mix** - Select to use tone, noise or tone & noise.
- [x] `0Wxx` **Noise pitch** - Set noise pitch.
- [x] `0Hxy` **Auto envelope** - #3, Set SSG-EG type and the shift amount of envelope period.
- [x] `0Ixx` `0Jxx` **Hardware envelope period** - #3, Set SSG-EG period.

**Comment by pedipanol** [comment]
I hope the Tone/Noise frequency command gets implemented soon, I'm missing that one a lot for the tracks I've been making!

**Comment by rerrahkr** [comment]
I will make Tone/Noise frequency, Hardware envelope shape and Hardware envelope frequency correspond to `Hxy`, `Ixx`,  `Jxx` and `Vxx` effects for Sunsoft 5B on FamiTracker.

**Comment by rerrahkr** [comment]
I try to add new FM effects (for FB, AR, ML, TL) to be the same as those of Deflemask, like `11xx`, `12xx`.
I will add effects that set the value directly in the register. It sets the address for the first effect and the register value for the second effect.

**Comment by papiezak** [comment]
I think it would be nice to have DRx control as well, since it would be useful in changing timbre of FM instruments using SSG-EG.

**Comment by papiezak** [comment]
Sorry if it may ba a stupid question, but to use 0X/0Y/0Z effects? Even when I'm using using all 3 of these on a default instrument there is no difference in its timbre.

**Comment by rerrahkr** [comment]
`0Xxx` and `0Yxx` set register address as *xx*. The difference of these effects is the bank of registers. From register map in section 1-5 of [YM2608 application manual](http://nemesis.hacking-cult.org/MegaDrive/Documentation/YM2608J%20Translated.PDF), `0Xxx` set the address of A1="0" (SSG, Rythm, FM 1-3ch), and `0Yxx` set that of A1="1" (ADPCM,  FM 4-6ch).
`0Zxx`set the value *xx* to the register whose address is specified by the previous `0Xxx` or `0Yxx`.

Therefore, it needs 2 effects to change the register value. For example, if you want to change the value of register $40 in bank 0 to $7F, you set effects as `0X40 0Z7F`.
